stages:
  - test
  - deploy

e2e-test:
  stage: test
  image: maven:3-jdk-11
  tags:
    - build
  script:
    - mvn clean verify -Dmaven.test.failure.ignore=true
    - mvn sonar:sonar -Dsonar.host.url=https://codeanalysis.maibornwolff.de/ -Dsonar.qualitygate.wait=true -Dsonar.login=9278d3d8917762ae0a508267deed0535a5c862df
    - mvn allure:report
  artifacts:
    paths:
      - target/site/allure-maven-plugin/

pages:
  stage: deploy
  dependencies:
    - e2e-test
  script:
    - mkdir public
    - mv target/site/allure-maven-plugin/* public/
  artifacts:
    paths:
      - public
    expire_in: 1 days
  tags:
    - build
  when: always
